[build]
  command = "next build"
  publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[context.production.environment]
  SECRET="864891de5cbcc5ba0dc546528398099ff295ed3e"

  NEXTAUTH_URL="https://recipebooktest.netlify.app"
  # Google oAuth
  GOOGLE_CLIENT_ID="601886753331-4kcu1tf241kbd201vjtomiokkb3rbmet.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET="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"

  # Database
  DATABASE_URL="mysql://gpi01is8271z:pscale_pw_B5i1ynssR9XU91Bv2ibalgimVAffWkBMHmLPJJ8IaW4@ayucsyu3ooe7.eu-central-1.psdb.cloud/recipebook?sslaccept=strict"
